name: Format with Prettier

# This action works with pull requests and pushes
on:
  #push:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
        
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install

    - name: Run prettier
      run: npx prettier --write "src/**/*.{ts,js,json,css,html}"