name: Code Quality checks

# This action works with pull requests and pushes
on:
  #push:
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          node-version: "14.x"
          
      - run: npm i
      - run: npm run prettier
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}